### ISSUE TITLE
Wrong parsing of loops when extra newlines are in between.

### ISSUE THREAD

**Issue by daxida** [ellnix/clash#5]
**To Reproduce**
[CG contrib](https://codingame.com/contribute/view/67293516d9a773d8a3de01469bde7324065a)

**Expected behavior**
![image](https://github.com/ellnix/clash/assets/80173028/054e05f6-d6b8-4a74-9779-fcef21181ca0)

**Additional context**
![image](https://github.com/ellnix/clash/assets/80173028/bf264d33-baba-4f21-a622-b49ef4b1ac5e)

**Comment by ellnix** [comment]
It looks like loop can apply to the line below it? I didn't expect that. Will fix.

**Comment by ellnix** [comment]
Completed.
